version: "2.6.1"

services:

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: transport_manager
      MYSQL_ROOT_PASSWORD: ${TM_MYSQL_PASSWORD}
      #TransportManagerUser123
    ports:
      - 3306:3306